version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,sts,cloudformation,ssm,iam
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMODB_SHARE_DB=1
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      localnet:
        ipv4_address: 10.0.2.20

  cdk:
    build:
      context: ./cdk
      dockerfile: Dockerfile
    working_dir: /cdk
    container_name: cdk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - AWS_ACCOUNT_ID=000000000000
    dns:
    - 10.0.2.20
    networks:
      localnet:

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - AWS_ACCESS_KEY_ID=test
  #     - AWS_SECRET_ACCESS_KEY=test
  #     - AWS_REGION=us-east-1
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - AWS_ENDPOINT_URL=http://localstack:4566
  #     - AWS_ENDPOINT_URL_S3=http://localstack:4566
  #     - DYNAMODB_ENDPOINT=http://localstack:4566
  #   depends_on:
  #     cdk:
  #       condition: service_completed_successfully
  #   networks:
  #     - localnet

networks:
  localnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
        